-- liquibase formatted sql

-- changeset cedricbrasey:1771532961448-2 splitStatements:false
insert into animal_species (id, name, is_active) values
    ('ALP','Alpaca',false),
    ('BFF','Buffalo',false),
    ('BRDS','Avian Birds',false),
    ('BSN','Bison',false),
    ('CHK','Chicken',false),
    ('CML','Camel',false),
    ('CT','Cat',false),
    ('CTT','Cattle',true),
    ('DCK','Duck',false),
    ('DG','Dog',false),
    ('DR','Deer',false),
    ('GNC','Guanaco',false),
    ('GNF','Guinea Fowl',false),
    ('GS','Goose',false),
    ('GT','Goat',false),
    ('HRS','Horse',false),
    ('LLM','Llama',false),
    ('NK','Newt/Salamander',false),
    ('OMS','Opossum',false),
    ('OST','Ostrich',false),
    ('OTHBRDS','Other Birds',false),
    ('OTHBVN','Other Bovine',false),
    ('PG','Pig',false),
    ('PGN','Pigeon',false),
    ('PHS','Pheasant',false),
    ('PRT','Parrot',false),
    ('QL','Quail',false),
    ('SHP','Sheep',false),
    ('TRK','Turkey',false),
    ('VIC','Vicuna',false),
    ('WLDBR','Wild Boar',false);