// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Defra.Identity.Endpoint.Tests.Tests.cphs
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Trait("Category", "cph")]
    [Trait("Category", "command")]
    public partial class CPHCommandTestsFeature : object, Xunit.IClassFixture<CPHCommandTestsFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = new string[] {
                "cph",
                "command"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Tests/cphs", "CPH command tests", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "command-tests.feature"
#line hidden
        
        public CPHCommandTestsFeature(CPHCommandTestsFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Tests/cphs/command-tests.feature.ndjson", 18);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Theory(DisplayName="Expire a cph using the <scenario> results in a <http_result> result")]
        [Trait("FeatureTitle", "CPH command tests")]
        [Trait("Description", "Expire a cph using the <scenario> results in a <http_result> result")]
        [Trait("Category", "single-result")]
        [Trait("Category", "command-expire")]
        [InlineData("available internal id", "204459b1-3a07-4e65-9122-91c1699e3d3f", "NoContent", "0", new string[] {
                "success"})]
        [InlineData("available cph number", "44/000/0004", "NoContent", "1", new string[] {
                "success"})]
        [InlineData("deleted internal id", "82181a8b-7f7f-470c-9263-2b94675599df", "NotFound", "2", new string[] {
                "error",
                "error-not-found"})]
        [InlineData("deleted cph number", "44/000/0006", "NotFound", "3", new string[] {
                "error",
                "error-not-found"})]
        [InlineData("unknown internal id", "d4a7f0d7-9999-9999-9999-547a5f494738", "NotFound", "4", new string[] {
                "error",
                "error-not-found"})]
        [InlineData("unknown cph number", "99/999/9876", "NotFound", "5", new string[] {
                "error",
                "error-not-found"})]
        [InlineData("expired internal id", "7973060a-d483-4ad4-9716-c70415ed620a", "Conflict", "6", new string[] {
                "error",
                "error-conflict"})]
        [InlineData("expired cph number", "44/000/0005", "Conflict", "7", new string[] {
                "error",
                "error-conflict"})]
        public async global::System.Threading.Tasks.Task ExpireACphUsingTheScenarioResultsInAHttp_ResultResult(string scenario, string uri_Value, string http_Result, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "single-result",
                    "command-expire"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("scenario", scenario);
            argumentsOfScenario.Add("uri_value", uri_Value);
            argumentsOfScenario.Add("http_result", http_Result);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Expire a cph using the <scenario> results in a <http_result> result", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await testRunner.GivenAsync("I am an Owner user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
    await testRunner.AndAsync(string.Format("the request url is \'/cphs/{0}:expire\'", uri_Value), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
    await testRunner.AndAsync("I am using the default header settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.WhenAsync("I \'POST\' this request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
    await testRunner.ThenAsync(string.Format("I receive the HTTP status code \'{0}\'", http_Result), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Theory(DisplayName="Delete a cph using the <scenario> results in a <http_result> result")]
        [Trait("FeatureTitle", "CPH command tests")]
        [Trait("Description", "Delete a cph using the <scenario> results in a <http_result> result")]
        [Trait("Category", "single-result")]
        [Trait("Category", "command-delete")]
        [InlineData("available internal id", "4435a146-d0ac-4260-8a27-c550e0ed9563", "NoContent", "8", new string[] {
                "success"})]
        [InlineData("available cph number", "44/000/0003", "NoContent", "9", new string[] {
                "success"})]
        [InlineData("expired internal id", "d9a711ec-722d-49b6-abcc-23f0795e3886", "NoContent", "10", new string[] {
                "success"})]
        [InlineData("expired cph number", "44/000/0024", "NoContent", "11", new string[] {
                "success"})]
        [InlineData("deleted internal id", "82181a8b-7f7f-470c-9263-2b94675599df", "NotFound", "12", new string[] {
                "error",
                "error-not-found"})]
        [InlineData("deleted cph number", "44/000/0006", "NotFound", "13", new string[] {
                "error",
                "error-not-found"})]
        [InlineData("unknown internal id", "d4a7f0d7-9999-9999-9999-547a5f494738", "NotFound", "14", new string[] {
                "error",
                "error-not-found"})]
        [InlineData("unknown cph number", "99/999/9876", "NotFound", "15", new string[] {
                "error",
                "error-not-found"})]
        public async global::System.Threading.Tasks.Task DeleteACphUsingTheScenarioResultsInAHttp_ResultResult(string scenario, string uri_Value, string http_Result, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "single-result",
                    "command-delete"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("scenario", scenario);
            argumentsOfScenario.Add("uri_value", uri_Value);
            argumentsOfScenario.Add("http_result", http_Result);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delete a cph using the <scenario> results in a <http_result> result", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.GivenAsync("I am an Owner user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
    await testRunner.AndAsync(string.Format("the request url is \'/cphs/{0}\'", uri_Value), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.AndAsync("I am using the default header settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
    await testRunner.WhenAsync("I \'DELETE\' this request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
    await testRunner.ThenAsync(string.Format("I receive the HTTP status code \'{0}\'", http_Result), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CPHCommandTestsFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await CPHCommandTestsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
