// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Defra.Identity.Endpoint.Tests.Tests.Cphs
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "cph")]
    [global::Xunit.TraitAttribute("Category", "query")]
    public partial class CPHQueryTestsFeature : object, Xunit.IClassFixture<CPHQueryTestsFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = new string[] {
                "cph",
                "query"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Tests/cphs", "CPH query tests", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "query-tests.feature"
#line hidden
        
        public CPHQueryTestsFeature(CPHQueryTestsFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Tests/cphs/query-tests.feature.ndjson", 12);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Get a maximum of 5 cphs from the first page excluding expired")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CPH query tests")]
        [global::Xunit.TraitAttribute("Description", "Get a maximum of 5 cphs from the first page excluding expired")]
        [global::Xunit.TraitAttribute("Category", "paged-result")]
        [global::Xunit.TraitAttribute("Category", "success")]
        [global::Xunit.TraitAttribute("Category", "data-live-only")]
        public async global::System.Threading.Tasks.Task GetAMaximumOf5CphsFromTheFirstPageExcludingExpired()
        {
            string[] tagsOfScenario = new string[] {
                    "paged-result",
                    "success",
                    "data-live-only"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get a maximum of 5 cphs from the first page excluding expired", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await testRunner.GivenAsync("I am an Owner user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
    await testRunner.AndAsync("the request url is \'/cphs?pageNumber=1&pageSize=5\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
    await testRunner.AndAsync("I am using the default header settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.WhenAsync("I \'GET\' this request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
    await testRunner.ThenAsync("I receive the HTTP status code \'OK\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 11
    await testRunner.AndAsync("I have received JSON data in the response", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
    await testRunner.AndAsync("the paged response is on page 1 has a total count of 6 and contains 5 objects", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table1.AddRow(new string[] {
                            "items[0].cph_number",
                            "44/000/0001"});
                table1.AddRow(new string[] {
                            "items[1].cph_number",
                            "44/000/0002"});
                table1.AddRow(new string[] {
                            "items[2].cph_number",
                            "44/000/0003"});
                table1.AddRow(new string[] {
                            "items[3].cph_number",
                            "44/000/0004"});
                table1.AddRow(new string[] {
                            "items[4].cph_number",
                            "44/000/0011"});
#line 13
    await testRunner.AndAsync("the response contains the following values:", ((string)(null)), table1, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Get a maximum of 5 cphs from the second page excluding expired")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CPH query tests")]
        [global::Xunit.TraitAttribute("Description", "Get a maximum of 5 cphs from the second page excluding expired")]
        [global::Xunit.TraitAttribute("Category", "paged-result")]
        [global::Xunit.TraitAttribute("Category", "success")]
        [global::Xunit.TraitAttribute("Category", "data-live-only")]
        public async global::System.Threading.Tasks.Task GetAMaximumOf5CphsFromTheSecondPageExcludingExpired()
        {
            string[] tagsOfScenario = new string[] {
                    "paged-result",
                    "success",
                    "data-live-only"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get a maximum of 5 cphs from the second page excluding expired", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
    await testRunner.GivenAsync("I am an Owner user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 24
    await testRunner.AndAsync("the request url is \'/cphs?pageNumber=2&pageSize=5\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
    await testRunner.AndAsync("I am using the default header settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
    await testRunner.WhenAsync("I \'GET\' this request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.ThenAsync("I receive the HTTP status code \'OK\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 28
    await testRunner.AndAsync("I have received JSON data in the response", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
    await testRunner.AndAsync("the paged response is on page 2 has a total count of 6 and contains 1 objects", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table2.AddRow(new string[] {
                            "items[0].cph_number",
                            "44/000/0023"});
#line 30
    await testRunner.AndAsync("the response contains the following values:", ((string)(null)), table2, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Get a maximum of 5 cphs from the first page including expired")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CPH query tests")]
        [global::Xunit.TraitAttribute("Description", "Get a maximum of 5 cphs from the first page including expired")]
        [global::Xunit.TraitAttribute("Category", "paged-result")]
        [global::Xunit.TraitAttribute("Category", "success")]
        [global::Xunit.TraitAttribute("Category", "data-all")]
        public async global::System.Threading.Tasks.Task GetAMaximumOf5CphsFromTheFirstPageIncludingExpired()
        {
            string[] tagsOfScenario = new string[] {
                    "paged-result",
                    "success",
                    "data-all"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get a maximum of 5 cphs from the first page including expired", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 36
    await testRunner.GivenAsync("I am an Owner user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 37
    await testRunner.AndAsync("the request url is \'/cphs?pageNumber=1&pageSize=5&expired=true\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
    await testRunner.AndAsync("I am using the default header settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
    await testRunner.WhenAsync("I \'GET\' this request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
    await testRunner.ThenAsync("I receive the HTTP status code \'OK\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 41
    await testRunner.AndAsync("I have received JSON data in the response", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
    await testRunner.AndAsync("the paged response is on page 1 has a total count of 9 and contains 5 objects", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table3.AddRow(new string[] {
                            "items[0].cph_number",
                            "44/000/0001"});
                table3.AddRow(new string[] {
                            "items[1].cph_number",
                            "44/000/0002"});
                table3.AddRow(new string[] {
                            "items[2].cph_number",
                            "44/000/0003"});
                table3.AddRow(new string[] {
                            "items[3].cph_number",
                            "44/000/0004"});
                table3.AddRow(new string[] {
                            "items[4].cph_number",
                            "44/000/0005"});
#line 43
    await testRunner.AndAsync("the response contains the following values:", ((string)(null)), table3, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Get a maximum of 5 cphs from the second page including expired")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CPH query tests")]
        [global::Xunit.TraitAttribute("Description", "Get a maximum of 5 cphs from the second page including expired")]
        [global::Xunit.TraitAttribute("Category", "paged-result")]
        [global::Xunit.TraitAttribute("Category", "success")]
        [global::Xunit.TraitAttribute("Category", "data-all")]
        public async global::System.Threading.Tasks.Task GetAMaximumOf5CphsFromTheSecondPageIncludingExpired()
        {
            string[] tagsOfScenario = new string[] {
                    "paged-result",
                    "success",
                    "data-all"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get a maximum of 5 cphs from the second page including expired", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 53
    await testRunner.GivenAsync("I am an Owner user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 54
    await testRunner.AndAsync("the request url is \'/cphs?pageNumber=2&pageSize=5&expired=true\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
    await testRunner.AndAsync("I am using the default header settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
    await testRunner.WhenAsync("I \'GET\' this request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
    await testRunner.ThenAsync("I receive the HTTP status code \'OK\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 58
    await testRunner.AndAsync("I have received JSON data in the response", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
    await testRunner.AndAsync("the paged response is on page 2 has a total count of 9 and contains 4 objects", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table4.AddRow(new string[] {
                            "items[0].cph_number",
                            "44/000/0011"});
                table4.AddRow(new string[] {
                            "items[1].cph_number",
                            "44/000/0023"});
                table4.AddRow(new string[] {
                            "items[2].cph_number",
                            "44/000/0024"});
                table4.AddRow(new string[] {
                            "items[3].cph_number",
                            "44/000/0025"});
#line 60
    await testRunner.AndAsync("the response contains the following values:", ((string)(null)), table4, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="Getting a CPH by an id returns a CPH")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CPH query tests")]
        [global::Xunit.TraitAttribute("Description", "Getting a CPH by an id returns a CPH")]
        [global::Xunit.TraitAttribute("Category", "single-result")]
        [global::Xunit.TraitAttribute("Category", "success")]
        [global::Xunit.TraitAttribute("Category", "data-live-only")]
        [global::Xunit.InlineDataAttribute("internal id", "4435a146-d0ac-4260-8a27-c550e0ed9563", "cph_number", "44/000/0001", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("cph number", "44/000/0001", "id", "4435a146-d0ac-4260-8a27-c550e0ed9563", "5", new string[0])]
        public async global::System.Threading.Tasks.Task GettingACPHByAnIdReturnsACPH(string id, string uri_Value, string property_Name, string check_Value, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "single-result",
                    "success",
                    "data-live-only"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("id", id);
            argumentsOfScenario.Add("uri_value", uri_Value);
            argumentsOfScenario.Add("property_name", property_Name);
            argumentsOfScenario.Add("check_value", check_Value);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Getting a CPH by an id returns a CPH", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 68
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 69
    await testRunner.GivenAsync("I am an Owner user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 70
    await testRunner.AndAsync(string.Format("the request url is \'/cphs/{0}\'", uri_Value), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
    await testRunner.AndAsync("I am using the default header settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
    await testRunner.WhenAsync("I \'GET\' this request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
    await testRunner.ThenAsync("I receive the HTTP status code \'OK\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 74
    await testRunner.AndAsync("I have received JSON data in the response", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
    await testRunner.AndAsync(string.Format("the value of property \"{0}\" is the same as \"{1}\"", property_Name, check_Value), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="Getting a CPH by an unkown id returns a 404")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CPH query tests")]
        [global::Xunit.TraitAttribute("Description", "Getting a CPH by an unkown id returns a 404")]
        [global::Xunit.TraitAttribute("Category", "error")]
        [global::Xunit.TraitAttribute("Category", "error-not-found")]
        [global::Xunit.InlineDataAttribute("internal id", "4435a146-9999-9999-8a27-c550e0ed9563", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("cph number", "99/999/9999", "7", new string[0])]
        public async global::System.Threading.Tasks.Task GettingACPHByAnUnkownIdReturnsA404(string id, string uri_Value, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "error",
                    "error-not-found"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("id", id);
            argumentsOfScenario.Add("uri_value", uri_Value);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Getting a CPH by an unkown id returns a 404", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 82
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 83
    await testRunner.GivenAsync("I am an Owner user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 84
    await testRunner.AndAsync(string.Format("the request url is \'/cphs/{0}\'", uri_Value), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
    await testRunner.AndAsync("I am using the default header settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
    await testRunner.WhenAsync("I \'GET\' this request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 87
    await testRunner.ThenAsync("I receive the HTTP status code \'NotFound\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 88
    await testRunner.AndAsync("I have an empty response", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Get a maximum of 5 cphs from the first page excluding expired and order by descen" +
            "ding on cph_number")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CPH query tests")]
        [global::Xunit.TraitAttribute("Description", "Get a maximum of 5 cphs from the first page excluding expired and order by descen" +
            "ding on cph_number")]
        [global::Xunit.TraitAttribute("Category", "paged-result")]
        [global::Xunit.TraitAttribute("Category", "sorted")]
        [global::Xunit.TraitAttribute("Category", "success")]
        [global::Xunit.TraitAttribute("Category", "data-live-only")]
        public async global::System.Threading.Tasks.Task GetAMaximumOf5CphsFromTheFirstPageExcludingExpiredAndOrderByDescendingOnCph_Number()
        {
            string[] tagsOfScenario = new string[] {
                    "paged-result",
                    "sorted",
                    "success",
                    "data-live-only"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get a maximum of 5 cphs from the first page excluding expired and order by descen" +
                    "ding on cph_number", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 95
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 96
    await testRunner.GivenAsync("I am an Owner user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 97
    await testRunner.AndAsync("the request url is \'/cphs?pageNumber=1&pageSize=5&orderByDescending=true\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
    await testRunner.AndAsync("I am using the default header settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
    await testRunner.WhenAsync("I \'GET\' this request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 100
    await testRunner.ThenAsync("I receive the HTTP status code \'OK\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 101
    await testRunner.AndAsync("I have received JSON data in the response", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 102
    await testRunner.AndAsync("the paged response is on page 1 has a total count of 6 and contains 5 objects", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table5.AddRow(new string[] {
                            "items[0].cph_number",
                            "44/000/0023"});
                table5.AddRow(new string[] {
                            "items[1].cph_number",
                            "44/000/0011"});
                table5.AddRow(new string[] {
                            "items[2].cph_number",
                            "44/000/0004"});
                table5.AddRow(new string[] {
                            "items[3].cph_number",
                            "44/000/0003"});
                table5.AddRow(new string[] {
                            "items[4].cph_number",
                            "44/000/0002"});
#line 103
    await testRunner.AndAsync("the response contains the following values:", ((string)(null)), table5, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Get a maximum of 5 cphs from the first page including expired and order by descen" +
            "ding on cph_number")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CPH query tests")]
        [global::Xunit.TraitAttribute("Description", "Get a maximum of 5 cphs from the first page including expired and order by descen" +
            "ding on cph_number")]
        [global::Xunit.TraitAttribute("Category", "paged-result")]
        [global::Xunit.TraitAttribute("Category", "sorted")]
        [global::Xunit.TraitAttribute("Category", "success")]
        [global::Xunit.TraitAttribute("Category", "data-all")]
        public async global::System.Threading.Tasks.Task GetAMaximumOf5CphsFromTheFirstPageIncludingExpiredAndOrderByDescendingOnCph_Number()
        {
            string[] tagsOfScenario = new string[] {
                    "paged-result",
                    "sorted",
                    "success",
                    "data-all"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get a maximum of 5 cphs from the first page including expired and order by descen" +
                    "ding on cph_number", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 112
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 113
    await testRunner.GivenAsync("I am an Owner user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 114
    await testRunner.AndAsync("the request url is \'/cphs?pageNumber=1&pageSize=5&expired&orderByDescending=true\'" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 115
    await testRunner.AndAsync("I am using the default header settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
    await testRunner.WhenAsync("I \'GET\' this request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 117
    await testRunner.ThenAsync("I receive the HTTP status code \'OK\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 118
    await testRunner.AndAsync("I have received JSON data in the response", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 119
    await testRunner.AndAsync("the paged response is on page 1 has a total count of 9 and contains 5 objects", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table6.AddRow(new string[] {
                            "items[0].cph_number",
                            "44/000/0025"});
                table6.AddRow(new string[] {
                            "items[1].cph_number",
                            "44/000/0024"});
                table6.AddRow(new string[] {
                            "items[2].cph_number",
                            "44/000/0023"});
                table6.AddRow(new string[] {
                            "items[3].cph_number",
                            "44/000/0011"});
                table6.AddRow(new string[] {
                            "items[4].cph_number",
                            "44/000/0005"});
#line 120
    await testRunner.AndAsync("the response contains the following values:", ((string)(null)), table6, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CPHQueryTestsFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await CPHQueryTestsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
