
### GET request to users to get top admin
GET {{host}}/users
X-Correlation-ID: {{Correlation-ID}}
x-api-key: {{api-key}}
X-Operator-Id: {{Operator-Id}}

> ../../Asserts/Should_be_200_OK_and_get_top_id.js


### Create new User
POST {{host}}/users
Content-Type: application/json
X-Correlation-ID: {{Correlation-ID}}
x-api-key: {{api-key}}
X-Operator-Id: {{id}}

{
  "first_name": "{{$random.address.firstName}}",
  "last_name":  "{{$random.address.lastName}}",
  "email": "{{$random.internet.safeEmailAddress}}",
  "display_name": "{{$random.address.firstName}}"
}

> ../../Asserts/Should_be_201_created.js

### GET request to users to get new added user
GET {{host}}/users?status=new
X-Correlation-ID: {{Correlation-ID}}
x-api-key: {{api-key}}
X-Operator-Id: {{Operator-Id}}

> ../../Asserts/Should_be_200_OK_and_get_top_id.js

### PUT request to update an existing user
PUT {{host}}/users/{{id}}
Content-Type: application/json
X-Correlation-ID: {{Correlation-ID}}
x-api-key: {{api-key}}
X-Operator-Id: {{Operator-Id}}

{
  "first_name": "{{$random.address.firstName}}",
  "last_name":  "{{$random.address.lastName}}",
  "email": "{{$random.internet.safeEmailAddress}}",
  "display_name": "{{$random.address.firstName}}"
}

> ../../Asserts/Should_be_200_OK.js

### Activate user  
POST {{host}}/users/{{id}}:activate
Content-Type: application/json
X-Correlation-ID: {{Correlation-ID}}
x-api-key: {{api-key}}
X-Operator-Id: {{Operator-Id}}


> ../../Asserts/Should_be_204_no_content.js

### suspend user  
POST {{host}}/users/{{id}}:suspend
Content-Type: application/json
X-Correlation-ID: {{Correlation-ID}}
x-api-key: {{api-key}}
X-Operator-Id: {{Operator-Id}}


> ../../Asserts/Should_be_204_no_content.js

### DELETE the user 
DELETE {{host}}/users/{{id}}
Content-Type: application/json
X-Correlation-ID: {{Correlation-ID}}
x-api-key: {{api-key}}
X-Operator-Id: {{Operator-Id}}


> ../../Asserts/Should_be_204_no_content.js