### GET request to users
GET {{host}}/users
 
###

< {% 
    request.variables.set("id", "3af6a188-391c-4e71-967d-2d5994510dca")

%}

GET {{host}}/users/{{id}}
X-Correlation-ID: test
x-api-key: test
X-Operator-Id: gary

###

