### GET request to users
GET {{host}}/users
 
###

< {% 
    request.variables.set("id", "af146cf4-6aa3-4e16-a632-a126fbbc852b")

%}

GET {{host}}/users/{{id}}
X-Correlation-ID: test
x-api-key: test
X-Operator-Id: gary