### GET request to users
GET {{host}}/users
X-Correlation-ID: {{Correlation-ID}}
x-api-key: {{api-key}}
X-Operator-Id: {{Operator-Id}}

> ../../Asserts/Should_be_200_OK_and_get_top_id.js
##



### PUT request to create a new user
PUT {{host}}/users/{{id}}
Content-Type: application/json
X-Correlation-ID: {{Correlation-ID}}
x-api-key: {{api-key}}
X-Operator-Id: {{Operator-Id}}

{
  "first_name": "{{$random.address.firstName}}",
  "last_name":  "{{$random.address.lastName}}",
  "email": "{{$random.internet.safeEmailAddress}}",
  "display_name": "{{$random.address.firstName}}"
}

> ../../Asserts/Should_be_200_OK.js

###