-- liquibase formatted sql

-- changeset cedricbrasey:1773744435706-04-01 splitStatements:false
create table external_messaging
(
    id                bigint generated by default as identity
        constraint external_messaging_pk
            primary key,
    message_type      smallint default 1       not null,
    message_recipient text                     not null,
    template_id       uuid                     not null,
    notify_id         uuid                     not null,
    request_payload   text,
    sent_at           timestamp with time zone,
    response_code     integer,
    response_message  text,
    exception_message text,
    created_at        timestamp with time zone not null,
    created_by        uuid
);

-- changeset cedricbrasey:1773744435706-04-02 splitStatements:false
ALTER TABLE "external_messaging"
    ADD CONSTRAINT "external_messaging_user_accounts_id_fk" FOREIGN KEY ("created_by") REFERENCES "user_accounts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;