// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Defra.Identity.Endpoint.Tests.Tests.Headers
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "system")]
    [global::Xunit.TraitAttribute("Category", "header")]
    public partial class CPFeatureHeaderTestsFeature : object, Xunit.IClassFixture<CPFeatureHeaderTestsFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = new string[] {
                "system",
                "header"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Tests/headers", "CPFeature: Header tests", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "header-tests.feature"
#line hidden
        
        public CPFeatureHeaderTestsFeature(CPFeatureHeaderTestsFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Tests/headers/header-tests.feature.ndjson", 6);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Make sure that a missing x-api-key header returns an error")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CPFeature: Header tests")]
        [global::Xunit.TraitAttribute("Description", "Make sure that a missing x-api-key header returns an error")]
        [global::Xunit.TraitAttribute("Category", "error")]
        [global::Xunit.TraitAttribute("Category", "error-bad-request")]
        public async global::System.Threading.Tasks.Task MakeSureThatAMissingX_Api_KeyHeaderReturnsAnError()
        {
            string[] tagsOfScenario = new string[] {
                    "error",
                    "error-bad-request"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Make sure that a missing x-api-key header returns an error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await testRunner.GivenAsync("I am an Owner user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
    await testRunner.AndAsync("the request url is \'/cphs?pageNumber=1&pageSize=5\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
    await testRunner.WhenAsync("I \'GET\' this request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
    await testRunner.ThenAsync("I receive the HTTP status code \'BadRequest\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table7.AddRow(new string[] {
                            "error.code",
                            "missing_header"});
                table7.AddRow(new string[] {
                            "error.message",
                            "Header x-api-key is required."});
                table7.AddRow(new string[] {
                            "error.path",
                            "/cphs"});
                table7.AddRow(new string[] {
                            "error.details.header",
                            "x-api-key"});
#line 10
    await testRunner.AndAsync("the response contains the following values:", ((string)(null)), table7, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Make sure that an invalid x-api-key header returns an error")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CPFeature: Header tests")]
        [global::Xunit.TraitAttribute("Description", "Make sure that an invalid x-api-key header returns an error")]
        [global::Xunit.TraitAttribute("Category", "error")]
        [global::Xunit.TraitAttribute("Category", "error-bad-request")]
        public async global::System.Threading.Tasks.Task MakeSureThatAnInvalidX_Api_KeyHeaderReturnsAnError()
        {
            string[] tagsOfScenario = new string[] {
                    "error",
                    "error-bad-request"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Make sure that an invalid x-api-key header returns an error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
    await testRunner.GivenAsync("I am an Owner user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
    await testRunner.AndAsync("the request url is \'/cphs?pageNumber=1&pageSize=5\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "header",
                            "value"});
                table8.AddRow(new string[] {
                            "x-api-key",
                            "not-a-key"});
#line 21
    await testRunner.AndAsync("I am using the following headers:", ((string)(null)), table8, "And ");
#line hidden
#line 24
    await testRunner.WhenAsync("I \'GET\' this request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
    await testRunner.ThenAsync("I receive the HTTP status code \'BadRequest\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table9.AddRow(new string[] {
                            "error.code",
                            "invalid_api_key"});
                table9.AddRow(new string[] {
                            "error.message",
                            "Header x-api-key is not valid."});
                table9.AddRow(new string[] {
                            "error.path",
                            "/cphs"});
                table9.AddRow(new string[] {
                            "error.details.header",
                            "x-api-key"});
#line 26
    await testRunner.AndAsync("the response contains the following values:", ((string)(null)), table9, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Make sure that a missing x-correlation-id returns an error")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CPFeature: Header tests")]
        [global::Xunit.TraitAttribute("Description", "Make sure that a missing x-correlation-id returns an error")]
        [global::Xunit.TraitAttribute("Category", "error")]
        [global::Xunit.TraitAttribute("Category", "error-bad-request")]
        public async global::System.Threading.Tasks.Task MakeSureThatAMissingX_Correlation_IdReturnsAnError()
        {
            string[] tagsOfScenario = new string[] {
                    "error",
                    "error-bad-request"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Make sure that a missing x-correlation-id returns an error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
    await testRunner.GivenAsync("I am an Owner user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
    await testRunner.AndAsync("the request url is \'/cphs?pageNumber=1&pageSize=5\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "header",
                            "value"});
                table10.AddRow(new string[] {
                            "x-api-key",
                            "test"});
#line 37
    await testRunner.AndAsync("I am using the following headers:", ((string)(null)), table10, "And ");
#line hidden
#line 40
    await testRunner.WhenAsync("I \'GET\' this request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
    await testRunner.ThenAsync("I receive the HTTP status code \'BadRequest\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table11.AddRow(new string[] {
                            "error.code",
                            "missing_header"});
                table11.AddRow(new string[] {
                            "error.message",
                            "Header x-correlation-id is required."});
                table11.AddRow(new string[] {
                            "error.path",
                            "/cphs"});
                table11.AddRow(new string[] {
                            "error.details.header",
                            "x-correlation-id"});
#line 42
    await testRunner.AndAsync("the response contains the following values:", ((string)(null)), table11, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="When i try to get a cph list with an x-api-key and x-correlation-id header then t" +
            "his should pass.")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CPFeature: Header tests")]
        [global::Xunit.TraitAttribute("Description", "When i try to get a cph list with an x-api-key and x-correlation-id header then t" +
            "his should pass.")]
        [global::Xunit.TraitAttribute("Category", "success")]
        public async global::System.Threading.Tasks.Task WhenITryToGetACphListWithAnX_Api_KeyAndX_Correlation_IdHeaderThenThisShouldPass_()
        {
            string[] tagsOfScenario = new string[] {
                    "success"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("When i try to get a cph list with an x-api-key and x-correlation-id header then t" +
                    "his should pass.", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 50
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 51
    await testRunner.GivenAsync("I am an Owner user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 52
    await testRunner.AndAsync("the request url is \'/cphs?pageNumber=1&pageSize=5\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "header",
                            "value"});
                table12.AddRow(new string[] {
                            "x-api-key",
                            "test"});
                table12.AddRow(new string[] {
                            "x-correlation-id",
                            "42b1849c-2dee-4cb8-a7b3-b011727b062b"});
#line 53
    await testRunner.AndAsync("I am using the following headers:", ((string)(null)), table12, "And ");
#line hidden
#line 57
    await testRunner.WhenAsync("I \'GET\' this request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
    await testRunner.ThenAsync("I receive the HTTP status code \'Ok\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CPFeatureHeaderTestsFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await CPFeatureHeaderTestsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
