### Should Get Missing API Key

GET {{host}}/users
X-Correlation-ID: {{Correlation-ID}}
x-api-key: ""
X-Operator-Id: {{Operator-Id}}

> ../../Asserts/headers/should_be_400_error_invalid_api_key.js


### Should Get Missing Correllation Id ""
GET {{host}}/users
x-api-key: {{api-key}}
X-Operator-Id: {{Operator-Id}}

> ../../Asserts/headers/should_be_400_error_missing_correllation_id.js

### Should Get empty Correllation Id '' Error
GET {{host}}/users
X-Correlation-ID: ''
x-api-key: {{api-key}}
X-Operator-Id: {{Operator-Id}}

> ../../Asserts/headers/should_be_400_error_missing_correllation_id.js

### Should Get empty Correllation Id Error
GET {{host}}/users
X-Correlation-ID: ""
x-api-key: {{api-key}}
X-Operator-Id: {{Operator-Id}}

> ../../Asserts/headers/should_be_400_error_missing_correllation_id.js


### Should Get empty Operator Id Error
PUT {{host}}/users/{{$random.internet.uuid}}
Content-Type: application/json
X-Correlation-ID: {{Correlation-ID}}
x-api-key: {{api-key}}


{
  "first_name": "{{$random.address.firstName}}",
  "last_name":  "{{$random.address.lastName}}",
  "email": "{{$random.internet.safeEmailAddress}}",
  "display_name": "{{$random.address.firstName}}"
}


> ../../Asserts/headers/should_be_400_error_missing_operator_id.js

