### Reset the local database
< ../../Asserts/data-scaffold.js
GET {{host}}/health

### Should Get Missing API Key
GET {{host}}/users
x-correlation-id: {{correlation-id}}
x-api-key: ""
x-operator-id: {{operator-id}}

> ../../Asserts/headers/should_be_400_error_invalid_api_key.js

### Should Get Missing Correllation Id ""
GET {{host}}/users
x-api-key: {{api-key}}
x-operator-id: {{operator-id}}

> ../../Asserts/headers/should_be_400_error_missing_correllation_id.js

### Should Get empty Correllation Id '' Error
GET {{host}}/users
x-correlation-id: ''
x-api-key: {{api-key}}
x-operator-id: {{operator-id}}

> ../../Asserts/headers/should_be_400_error_missing_correllation_id.js

### Should Get empty Correllation Id Error
GET {{host}}/users
x-correlation-id: ""
x-api-key: {{api-key}}
x-operator-id: {{operator-id}}

> ../../Asserts/headers/should_be_400_error_missing_correllation_id.js


### Should Get empty Operator Id Error
PUT {{host}}/users/{{$random.internet.uuid}}
Content-Type: application/json
x-correlation-id: {{correlation-id}}
x-api-key: {{api-key}}

{
  "first_name": "{{$random.address.firstName}}",
  "last_name":  "{{$random.address.lastName}}",
  "email": "{{$random.internet.safeEmailAddress}}",
  "display_name": "{{$random.address.firstName}}"
}

> ../../Asserts/headers/should_be_400_error_missing_operator_id.js

