-- liquibase formatted sql

-- changeset gary:1770120637903-1 splitStatements:true
CREATE TABLE "application" ("id" UUID DEFAULT public.uuid_generate_v4() NOT NULL, "name" TEXT NOT NULL, "client_id" UUID NOT NULL, "tenant_name" TEXT NOT NULL, "description" TEXT NOT NULL, "status_type_id" SMALLINT DEFAULT 1 NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_application" PRIMARY KEY ("id"));
COMMENT ON COLUMN "application"."name" IS 'Human readable name for the application e.g Keeper Portal';
COMMENT ON COLUMN "application"."client_id" IS 'Azure AD B2C application Client ID';
COMMENT ON COLUMN "application"."tenant_name" IS 'Azure AD B2C tenant name e.g defra.onmicrosoft.com';

-- changeset gary:1770120637903-2 splitStatements:false
CREATE TABLE "application_role" ("application_id" UUID NOT NULL, "role_id" SMALLINT NOT NULL, CONSTRAINT "PK_application_role" PRIMARY KEY ("application_id", "role_id"));

-- changeset gary:1770120637903-3 splitStatements:false
CREATE TABLE "county_parish_holding" ("id" UUID DEFAULT public.uuid_generate_v4() NOT NULL, "identifier" VARCHAR NOT NULL, "status_type_id" SMALLINT DEFAULT 1 NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "created_by" UUID NOT NULL, "processed_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_by" UUID, "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_county_parish_holding" PRIMARY KEY ("id"));

-- changeset gary:1770120637903-4 splitStatements:false
CREATE TABLE "delegation" ("id" UUID DEFAULT public.uuid_generate_v4() NOT NULL, "status_type_id" SMALLINT DEFAULT 1 NOT NULL, "county_parish_holding_id" UUID NOT NULL, "application_id" UUID NOT NULL, "invited_by_user_id" UUID NOT NULL, "invited_by_role_id" SMALLINT NOT NULL, "invited_user_id" UUID NOT NULL, "invited_email" VARCHAR NOT NULL, "invitation_token" CHAR(64) NOT NULL, "token_expires_at" CHAR(1) NOT NULL, "delegated_role_id" SMALLINT NOT NULL, "delegated_permissions" JSONB NOT NULL, "invited_at" TIMESTAMP WITH TIME ZONE NOT NULL, "activated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "registered_at" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked_at" TIMESTAMP WITH TIME ZONE NOT NULL, "ActivatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "expired_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "created_by" UUID NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_delegation" PRIMARY KEY ("id"));

-- changeset gary:1770120637903-5 splitStatements:false
CREATE TABLE "federation" ("id" UUID DEFAULT public.uuid_generate_v4() NOT NULL, "user_account_id" UUID NOT NULL, "tenant_name" TEXT NOT NULL, "object_id" UUID NOT NULL, "trust_level" TEXT DEFAULT 'standard' NOT NULL, "sync_status" TEXT DEFAULT 'linked' NOT NULL, "last_synced_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_federation" PRIMARY KEY ("id"));

-- changeset gary:1770120637903-6 splitStatements:false
CREATE TABLE "krds_sync_log" ("id" UUID NOT NULL, "correlation_id" UUID NOT NULL, "source_endpoint" TEXT NOT NULL, "http_status" INTEGER NOT NULL, "processed_ok" BOOLEAN NOT NULL, "message" TEXT NOT NULL, "received_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "processed_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_krds_sync_log" PRIMARY KEY ("id"));

-- changeset gary:1770120637903-7 splitStatements:false
CREATE TABLE "registration" ("id" UUID DEFAULT public.uuid_generate_v4() NOT NULL, "country_parish_holding_id" UUID NOT NULL, "application_id" UUID NOT NULL, "status_type_id" SMALLINT DEFAULT 1 NOT NULL, "enrolled_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "created_by" UUID NOT NULL, "updated_by" UUID, "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_registration" PRIMARY KEY ("id"));

-- changeset gary:1770120637903-8 splitStatements:false
CREATE TABLE "role" ("id" SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR NOT NULL, "description" VARCHAR NOT NULL, CONSTRAINT "PK_role" PRIMARY KEY ("id"));

-- changeset gary:1770120637903-9 splitStatements:false
CREATE TABLE "status_type" ("id" SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR NOT NULL, "description" VARCHAR NOT NULL, CONSTRAINT "PK_status_type" PRIMARY KEY ("id"));

-- changeset gary:1770120637903-10 splitStatements:false
CREATE TABLE "user_account" ("id" UUID DEFAULT public.uuid_generate_v4() NOT NULL, "email_address" VARCHAR NOT NULL, "status_type_id" SMALLINT DEFAULT 1 NOT NULL, "display_name" PUBLIC.CITEXT NOT NULL, "first_name" VARCHAR NOT NULL, "last_name" VARCHAR NOT NULL, "created_by" UUID NOT NULL, "updated_by" UUID, "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_user_account" PRIMARY KEY ("id"));

-- changeset gary:1770120637903-11 splitStatements:false
CREATE INDEX "IX_application_role_role_id" ON "application_role" USING btree("role_id");

-- changeset gary:1770120637903-12 splitStatements:false
CREATE INDEX "IX_application_status_type_id" ON "application" USING btree("status_type_id");

-- changeset gary:1770120637903-13 splitStatements:false
CREATE INDEX "IX_county_parish_holding_identifier" ON "county_parish_holding" USING btree("identifier");

-- changeset gary:1770120637903-14 splitStatements:false
CREATE INDEX "IX_county_parish_holding_status_type_id" ON "county_parish_holding" USING btree("status_type_id");

-- changeset gary:1770120637903-15 splitStatements:false
CREATE INDEX "IX_delegation_application_id" ON "delegation" USING btree("application_id");

-- changeset gary:1770120637903-16 splitStatements:false
CREATE INDEX "IX_delegation_county_parish_holding_id" ON "delegation" USING btree("county_parish_holding_id");

-- changeset gary:1770120637903-17 splitStatements:false
CREATE INDEX "IX_delegation_delegated_role_id" ON "delegation" USING btree("delegated_role_id");

-- changeset gary:1770120637903-18 splitStatements:false
CREATE INDEX "IX_delegation_invited_by_role_id" ON "delegation" USING btree("invited_by_role_id");

-- changeset gary:1770120637903-19 splitStatements:false
CREATE INDEX "IX_delegation_invited_by_user_id" ON "delegation" USING btree("invited_by_user_id");

-- changeset gary:1770120637903-20 splitStatements:false
CREATE INDEX "IX_delegation_invited_user_id" ON "delegation" USING btree("invited_user_id");

-- changeset gary:1770120637903-21 splitStatements:false
CREATE INDEX "IX_delegation_status_type_id" ON "delegation" USING btree("status_type_id");

-- changeset gary:1770120637903-22 splitStatements:false
CREATE INDEX "IX_federation_object_id_tenant_name" ON "federation" USING btree("object_id", "tenant_name");

-- changeset gary:1770120637903-23 splitStatements:false
CREATE INDEX "IX_federation_user_account_id" ON "federation" USING btree("user_account_id");

-- changeset gary:1770120637903-24 splitStatements:false
CREATE INDEX "IX_krds_sync_log_received_at" ON "krds_sync_log" USING btree("received_at");

-- changeset gary:1770120637903-25 splitStatements:false
CREATE INDEX "IX_registration_application_id" ON "registration" USING btree("application_id");

-- changeset gary:1770120637903-26 splitStatements:false
CREATE INDEX "IX_registration_country_parish_holding_id" ON "registration" USING btree("country_parish_holding_id");

-- changeset gary:1770120637903-27 splitStatements:false
CREATE INDEX "IX_registration_status_type_id" ON "registration" USING btree("status_type_id");

-- changeset gary:1770120637903-28 splitStatements:false
CREATE INDEX "IX_user_account_created_by" ON "user_account" USING btree("created_by");

-- changeset gary:1770120637903-29 splitStatements:false
CREATE UNIQUE INDEX "IX_user_account_email_address" ON "user_account" USING btree("email_address");

-- changeset gary:1770120637903-30 splitStatements:false
CREATE INDEX "IX_user_account_status_type_id" ON "user_account" USING btree("status_type_id");

-- changeset gary:1770120637903-31 splitStatements:false
CREATE INDEX "IX_user_account_updated_by" ON "user_account" USING btree("updated_by");

-- changeset gary:1770120637903-32 splitStatements:false
ALTER TABLE "application" ADD CONSTRAINT "FK_application_status_type_status_type_id" FOREIGN KEY ("status_type_id") REFERENCES "status_type" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset gary:1770120637903-33 splitStatements:false
ALTER TABLE "county_parish_holding" ADD CONSTRAINT "FK_county_parish_holding_status_type_status_type_id" FOREIGN KEY ("status_type_id") REFERENCES "status_type" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset gary:1770120637903-34 splitStatements:false
ALTER TABLE "delegation" ADD CONSTRAINT "FK_delegation_application_application_id" FOREIGN KEY ("application_id") REFERENCES "application" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset gary:1770120637903-35 splitStatements:false
ALTER TABLE "delegation" ADD CONSTRAINT "FK_delegation_county_parish_holding_county_parish_holding_id" FOREIGN KEY ("county_parish_holding_id") REFERENCES "county_parish_holding" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset gary:1770120637903-36 splitStatements:false
ALTER TABLE "delegation" ADD CONSTRAINT "FK_delegation_role_delegated_role_id" FOREIGN KEY ("delegated_role_id") REFERENCES "role" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset gary:1770120637903-37 splitStatements:false
ALTER TABLE "delegation" ADD CONSTRAINT "FK_delegation_role_invited_by_role_id" FOREIGN KEY ("invited_by_role_id") REFERENCES "role" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset gary:1770120637903-38 splitStatements:false
ALTER TABLE "delegation" ADD CONSTRAINT "FK_delegation_status_type_status_type_id" FOREIGN KEY ("status_type_id") REFERENCES "status_type" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset gary:1770120637903-39 splitStatements:false
ALTER TABLE "delegation" ADD CONSTRAINT "FK_delegation_user_account_invited_by_user_id" FOREIGN KEY ("invited_by_user_id") REFERENCES "user_account" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset gary:1770120637903-40 splitStatements:false
ALTER TABLE "delegation" ADD CONSTRAINT "FK_delegation_user_account_invited_user_id" FOREIGN KEY ("invited_user_id") REFERENCES "user_account" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset gary:1770120637903-41 splitStatements:false
ALTER TABLE "federation" ADD CONSTRAINT "FK_federation_user_account_user_account_id" FOREIGN KEY ("user_account_id") REFERENCES "user_account" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset gary:1770120637903-42 splitStatements:false
ALTER TABLE "registration" ADD CONSTRAINT "FK_registration_application_application_id" FOREIGN KEY ("application_id") REFERENCES "application" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset gary:1770120637903-43 splitStatements:false
ALTER TABLE "registration" ADD CONSTRAINT "FK_registration_county_parish_holding_country_parish_holding_id" FOREIGN KEY ("country_parish_holding_id") REFERENCES "county_parish_holding" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset gary:1770120637903-44 splitStatements:false
ALTER TABLE "registration" ADD CONSTRAINT "FK_registration_status_type_status_type_id" FOREIGN KEY ("status_type_id") REFERENCES "status_type" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset gary:1770120637903-45 splitStatements:false
ALTER TABLE "user_account" ADD CONSTRAINT "FK_user_account_status_type_status_type_id" FOREIGN KEY ("status_type_id") REFERENCES "status_type" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset gary:1770120637903-46 splitStatements:false
ALTER TABLE "user_account" ADD CONSTRAINT "FK_user_account_user_account_created_by" FOREIGN KEY ("created_by") REFERENCES "user_account" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset gary:1770120637903-47 splitStatements:false
ALTER TABLE "user_account" ADD CONSTRAINT "FK_user_account_user_account_updated_by" FOREIGN KEY ("updated_by") REFERENCES "user_account" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset gary:1770120637903-48 splitStatements:false
ALTER TABLE "application_role" ADD CONSTRAINT "application_role_mapping_application_id_fk" FOREIGN KEY ("application_id") REFERENCES "application" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset gary:1770120637903-49 splitStatements:false
ALTER TABLE "application_role" ADD CONSTRAINT "application_role_mapping_role_id_fk" FOREIGN KEY ("role_id") REFERENCES "role" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

