// <auto-generated />
using System;
using System.Text.Json;
using Defra.Identity.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Defra.Identity.Postgres.Database.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20260213113328_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.ApplicationRoles", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("ApplicationId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("application_roles", "public");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.ApplicationUserAccountHoldingAssignments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid>("CountyParishHoldingId")
                        .HasColumnType("uuid")
                        .HasColumnName("county_parish_holding_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CountyParishHoldingId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("application_user_account_holding_assignments", "public");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Applications", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id")
                        .HasComment("Azure AD B2C application Client ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("Human readable name for the application e.g Keeper Portal");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_name")
                        .HasComment("Azure AD B2C tenant name e.g defra.onmicrosoft.com");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.ToTable("applications", "public");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.CountyParishHoldings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("expired_at");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar")
                        .HasColumnName("identifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("Identifier");

                    b.ToTable("county_parish_holdings", "public");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.DelegationInvitations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AccpetedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("accpeted_at");

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("activated_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<JsonDocument>("DelegatedPermissions")
                        .HasColumnType("jsonb")
                        .HasColumnName("delegated_permissions");

                    b.Property<Guid>("DelegatedRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("delegated_role_id");

                    b.Property<Guid>("DelegationId")
                        .HasColumnType("uuid")
                        .HasColumnName("delegation_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("expired_at");

                    b.Property<string>("InvitationToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char")
                        .HasColumnName("invitation_token");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("invited_at");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasColumnName("invited_email");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_user_id");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("registered_at");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("revoked_at");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("token_expires_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DelegatedRoleId");

                    b.HasIndex("DelegationId");

                    b.HasIndex("DeletedById");

                    b.ToTable("delegation_invitations", "public");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Delegations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid?>("CountyParishHoldingsId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<Guid?>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RolesId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserAccountsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CountyParishHoldingsId");

                    b.HasIndex("RolesId");

                    b.HasIndex("RolesId1");

                    b.HasIndex("UserAccountsId");

                    b.HasIndex("UserId");

                    b.ToTable("delegations", "public");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.DelegationsCountyParishHoldings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CountyParishHoldingId")
                        .HasColumnType("uuid")
                        .HasColumnName("county_parish_holding_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<Guid>("DelegationId")
                        .HasColumnType("uuid")
                        .HasColumnName("delegation_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.HasKey("Id");

                    b.HasIndex("CountyParishHoldingId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DelegationId");

                    b.HasIndex("DeletedById");

                    b.ToTable("delegations_county_parish_holdings", "public");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.KrdsSyncLogs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("processed_at");

                    b.Property<bool>("ProcessedOk")
                        .HasColumnType("boolean")
                        .HasColumnName("processed_ok");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SourceEndpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_endpoint");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.ToTable("krds_sync_logs", "public");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles", "public");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.UserAccounts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("display_name");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasColumnName("email_address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasColumnName("first_name");

                    b.Property<Guid?>("KrdsId")
                        .HasColumnType("uuid")
                        .HasColumnName("krds_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("SamId")
                        .HasColumnType("uuid")
                        .HasColumnName("sam_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("EmailAddress")
                        .IsUnique()
                        .HasDatabaseName("IX_UserAccounts_EmailAddress");

                    b.ToTable("user_accounts", "public");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.ApplicationRoles", b =>
                {
                    b.HasOne("Defra.Identity.Postgres.Database.Entities.Applications", "Applications")
                        .WithMany("ApplicationRoles")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("application_role_mapping_application_id_fk");

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.Roles", "Roles")
                        .WithMany("ApplicationRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("application_role_mapping_role_id_fk");

                    b.Navigation("Applications");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.ApplicationUserAccountHoldingAssignments", b =>
                {
                    b.HasOne("Defra.Identity.Postgres.Database.Entities.Applications", "Application")
                        .WithMany("ApplicationUserAccountHoldingAssignments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.CountyParishHoldings", "Type")
                        .WithMany("ApplicationUserAccountHoldingAssignments")
                        .HasForeignKey("CountyParishHoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccounts", "CreatedByUser")
                        .WithMany("ApplicationUserAccountHoldingAssignmentsCreatedByUsers")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccounts", "DeletedByUser")
                        .WithMany("ApplicationUserAccountHoldingAssignmentsDeletedByUsers")
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("FK_application_user_account_holding_assignments_user_accounts~1");

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.Roles", "Role")
                        .WithMany("ApplicationUserAccountHoldingAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccounts", "UserAccount")
                        .WithMany("ApplicationUserAccountHoldingAssignments")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_application_user_account_holding_assignments_user_accounts~2");

                    b.Navigation("Application");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("Role");

                    b.Navigation("Type");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Applications", b =>
                {
                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccounts", "CreatedByUser")
                        .WithMany("ApplicationsCreatedByUsers")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccounts", "DeletedByUser")
                        .WithMany("ApplicationsDeletedByUsers")
                        .HasForeignKey("DeletedById");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.CountyParishHoldings", b =>
                {
                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccounts", "CreatedByUser")
                        .WithMany("CountyParishHoldingsCreatedByUsers")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccounts", "DeletedByUser")
                        .WithMany("CountyParishHoldingsDeletedByUsers")
                        .HasForeignKey("DeletedById");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.DelegationInvitations", b =>
                {
                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccounts", "CreatedByUser")
                        .WithMany("DelegationInvitationsCreatedByUsers")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.Roles", "DelegatedRole")
                        .WithMany("DelegationInvitations")
                        .HasForeignKey("DelegatedRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.Delegations", "Delegation")
                        .WithMany("DelegationInvitations")
                        .HasForeignKey("DelegationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccounts", "DeletedByUser")
                        .WithMany("DelegationInvitationsDeletedByUsers")
                        .HasForeignKey("DeletedById");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DelegatedRole");

                    b.Navigation("Delegation");

                    b.Navigation("DeletedByUser");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Delegations", b =>
                {
                    b.HasOne("Defra.Identity.Postgres.Database.Entities.Applications", "Applications")
                        .WithMany("Delegations")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.CountyParishHoldings", null)
                        .WithMany("Delegations")
                        .HasForeignKey("CountyParishHoldingsId");

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.Roles", null)
                        .WithMany("DelegatedRoles")
                        .HasForeignKey("RolesId");

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.Roles", null)
                        .WithMany("InvitedByRoles")
                        .HasForeignKey("RolesId1");

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccounts", null)
                        .WithMany("InvitedByUsers")
                        .HasForeignKey("UserAccountsId");

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccounts", "UserAccount")
                        .WithMany("Delegations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applications");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.DelegationsCountyParishHoldings", b =>
                {
                    b.HasOne("Defra.Identity.Postgres.Database.Entities.CountyParishHoldings", "CountyParishHolding")
                        .WithMany("DelegationsCountyParishHoldings")
                        .HasForeignKey("CountyParishHoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccounts", "CreatedByUser")
                        .WithMany("DelegationsCountyParishHoldingsCreatedByUsers")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.Delegations", "Delegation")
                        .WithMany("DelegationsCountyParishHoldings")
                        .HasForeignKey("DelegationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccounts", "DeletedByUser")
                        .WithMany("DelegationsCountyParishHoldingsDeletedByUsers")
                        .HasForeignKey("DeletedById");

                    b.Navigation("CountyParishHolding");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Delegation");

                    b.Navigation("DeletedByUser");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.UserAccounts", b =>
                {
                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccounts", "CreatedBy")
                        .WithMany("CreatedUsers")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccounts", "DeletedBy")
                        .WithMany("DeletedUsers")
                        .HasForeignKey("DeletedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Applications", b =>
                {
                    b.Navigation("ApplicationRoles");

                    b.Navigation("ApplicationUserAccountHoldingAssignments");

                    b.Navigation("Delegations");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.CountyParishHoldings", b =>
                {
                    b.Navigation("ApplicationUserAccountHoldingAssignments");

                    b.Navigation("Delegations");

                    b.Navigation("DelegationsCountyParishHoldings");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Delegations", b =>
                {
                    b.Navigation("DelegationInvitations");

                    b.Navigation("DelegationsCountyParishHoldings");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Roles", b =>
                {
                    b.Navigation("ApplicationRoles");

                    b.Navigation("ApplicationUserAccountHoldingAssignments");

                    b.Navigation("DelegatedRoles");

                    b.Navigation("DelegationInvitations");

                    b.Navigation("InvitedByRoles");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.UserAccounts", b =>
                {
                    b.Navigation("ApplicationUserAccountHoldingAssignments");

                    b.Navigation("ApplicationUserAccountHoldingAssignmentsCreatedByUsers");

                    b.Navigation("ApplicationUserAccountHoldingAssignmentsDeletedByUsers");

                    b.Navigation("ApplicationsCreatedByUsers");

                    b.Navigation("ApplicationsDeletedByUsers");

                    b.Navigation("CountyParishHoldingsCreatedByUsers");

                    b.Navigation("CountyParishHoldingsDeletedByUsers");

                    b.Navigation("CreatedUsers");

                    b.Navigation("DelegationInvitationsCreatedByUsers");

                    b.Navigation("DelegationInvitationsDeletedByUsers");

                    b.Navigation("Delegations");

                    b.Navigation("DelegationsCountyParishHoldingsCreatedByUsers");

                    b.Navigation("DelegationsCountyParishHoldingsDeletedByUsers");

                    b.Navigation("DeletedUsers");

                    b.Navigation("InvitedByUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
