// <auto-generated />
using System;
using Defra.Identity.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Defra.Identity.Postgres.Database.Migrations
{
    [DbContext(typeof(AuthContext))]
    [Migration("20260130100124_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("defra-ci")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id")
                        .HasComment("Azure AD B2C application Client ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("Human readable name for the application e.g Keeper Portal");

                    b.Property<short>("StatusTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status_type_id");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_name")
                        .HasComment("Azure AD B2C tenant name e.g defra.onmicrosoft.com");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("application", "defra-ci");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.HasKey("ApplicationId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("application_role", "defra-ci");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.CountyParishHolding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar")
                        .HasColumnName("identifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("processed_at");

                    b.Property<short>("StatusTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status_type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Identifier");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("county_parish_holding", "defra-ci");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Delegation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("activated_at");

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid>("CountyParishHoldingId")
                        .HasColumnType("uuid")
                        .HasColumnName("county_parish_holding_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<object>("DelegatedPermissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("delegated_permissions");

                    b.Property<short>("DelegatedRoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("delegated_role_id");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("expired_at");

                    b.Property<string>("InvitationToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char")
                        .HasColumnName("invitation_token");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("invited_at");

                    b.Property<short>("InvitedByRoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("invited_by_role_id");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasColumnName("invited_email");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_user_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("registered_at");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("revoked_at");

                    b.Property<short>("StatusTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status_type_id");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasMaxLength(64)
                        .HasColumnType("char")
                        .HasColumnName("token_expires_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CountyParishHoldingId");

                    b.HasIndex("DelegatedRoleId");

                    b.HasIndex("InvitedByRoleId");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("InvitedUserId");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("delegation", "defra-ci");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Federation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("last_synced_at");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("linked")
                        .HasColumnName("sync_status");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_name");

                    b.Property<string>("TrustLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("standard")
                        .HasColumnName("trust_level");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("ObjectId", "TenantName");

                    b.ToTable("federation", "defra-ci");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.KrdsSyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("processed_at");

                    b.Property<bool>("ProcessedOk")
                        .HasColumnType("boolean")
                        .HasColumnName("processed_ok");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SourceEndpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_endpoint");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.ToTable("krds_sync_log", "defra-ci");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid>("CountryParishHoldingId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_parish_holding_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("enrolled_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("expires_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<short>("StatusTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status_type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CountryParishHoldingId");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("registration", "defra-ci");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Role", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("role", "defra-ci");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.StatusType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("status_type", "defra-ci");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("display_name");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasColumnName("email_address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasColumnName("last_name");

                    b.Property<short>("StatusTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status_type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TimestampTz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("StatusTypeId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("user_account", "defra-ci");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Application", b =>
                {
                    b.HasOne("Defra.Identity.Postgres.Database.Entities.StatusType", "StatusType")
                        .WithMany("Applications")
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.ApplicationRole", b =>
                {
                    b.HasOne("Defra.Identity.Postgres.Database.Entities.Application", "Application")
                        .WithMany("ApplicationRoles")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("application_role_mapping_application_id_fk");

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.Role", "Role")
                        .WithMany("ApplicationRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("application_role_mapping_role_id_fk");

                    b.Navigation("Application");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.CountyParishHolding", b =>
                {
                    b.HasOne("Defra.Identity.Postgres.Database.Entities.StatusType", "StatusType")
                        .WithMany("CountyParishHoldings")
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Delegation", b =>
                {
                    b.HasOne("Defra.Identity.Postgres.Database.Entities.Application", "Application")
                        .WithMany("Delegations")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.CountyParishHolding", "CountyParishHolding")
                        .WithMany("Delegations")
                        .HasForeignKey("CountyParishHoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.Role", "DelegatedRole")
                        .WithMany("DelegatedRoles")
                        .HasForeignKey("DelegatedRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.Role", "InvitedByRole")
                        .WithMany("InvitedByRoles")
                        .HasForeignKey("InvitedByRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccount", "InvitedByUser")
                        .WithMany("InvitedByUsers")
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccount", "InvitedUser")
                        .WithMany("Delegations")
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.StatusType", "Status")
                        .WithMany("Delegations")
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("CountyParishHolding");

                    b.Navigation("DelegatedRole");

                    b.Navigation("InvitedByRole");

                    b.Navigation("InvitedByUser");

                    b.Navigation("InvitedUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Federation", b =>
                {
                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccount", "UserAccount")
                        .WithMany("Federations")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Registration", b =>
                {
                    b.HasOne("Defra.Identity.Postgres.Database.Entities.Application", "Application")
                        .WithMany("Registrations")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.CountyParishHolding", "CountyParishHolding")
                        .WithMany("Registrations")
                        .HasForeignKey("CountryParishHoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.StatusType", "Status")
                        .WithMany("Registrations")
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("CountyParishHolding");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.UserAccount", b =>
                {
                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccount", "CreatedByUser")
                        .WithMany("CreatedUsers")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.StatusType", "Status")
                        .WithMany("UserAccounts")
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Defra.Identity.Postgres.Database.Entities.UserAccount", "UpdatedByUser")
                        .WithMany("UpdatedUsers")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Status");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Application", b =>
                {
                    b.Navigation("ApplicationRoles");

                    b.Navigation("Delegations");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.CountyParishHolding", b =>
                {
                    b.Navigation("Delegations");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.Role", b =>
                {
                    b.Navigation("ApplicationRoles");

                    b.Navigation("DelegatedRoles");

                    b.Navigation("InvitedByRoles");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.StatusType", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("CountyParishHoldings");

                    b.Navigation("Delegations");

                    b.Navigation("Registrations");

                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("Defra.Identity.Postgres.Database.Entities.UserAccount", b =>
                {
                    b.Navigation("CreatedUsers");

                    b.Navigation("Delegations");

                    b.Navigation("Federations");

                    b.Navigation("InvitedByUsers");

                    b.Navigation("UpdatedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
